file1=open('myfile.txt','w')
l=['This is Delhi\n','This is london\n']
file1.write('Hello\n')
file1.writelines(l)
file1.close()

file1=open('myfile.txt','r+')
print('output is')
print(file1.read())
file1.seek(0)
print('output:')
print(file1.readline())
file1.seek(0)
print('output of readline(9) func is')
print(file1.readlines(25))
file1.seek(0)
print('output of readlines func is')
print(file1.readlines())
file1.close()
